sudo: false
language: scala
scala:
- 2.12.4
matrix:
  include:
  - env: SCALAJS_VERSION="0.6.22"
  - env: SCALAJS_VERSION="1.0.0-M2"
stages:
- name: test
- name: release
  if: "(type = push)"
jobs:
  include:
  - env: SCALAJS_VERSION="0.6.22"
    script: sbt compile
  - env: SCALAJS_VERSION="1.0.0-M2"
    script: sbt compile
  - stage: release
    env: SCALAJS_VERSION="0.6.22"
    script: "./travis/ci-publish.sh"
  - env: SCALAJS_VERSION="1.0.0-M2"
    script: "./travis/ci-publish.sh"
cache:
  directories:
  - "$HOME/.sbt/0.13/dependency"
  - "$HOME/.sbt/boot/"
  - "$HOME/.sbt/launchers"
  - "$HOME/.ivy2/cache"
  - "$HOME/.coursier"
before_cache:
- du -h -d 1 $HOME/.ivy2/cache
- du -h -d 2 $HOME/.sbt/
- find $HOME/.sbt -name "*.lock" -type f -delete
- find $HOME/.ivy2/cache -name "ivydata-*.properties" -type f -delete
- rm -rf $HOME/.ivy2/local
env:
  global:
  - secure: sAlI5rkN4OQsHhOA6VdKCIJ2xU9W3PWTx7gQ5eKSRsd3zLjNqDSeXM47C28qD0X4rIC1G4XLY6Lm7m2IKOCs8XvBrN8rIX47oLR8kdQ3+uN+IdrIvdEyO2T7EwHWs+/LNbifD8KEYYtHi3Mt/vmmi/01ASylTmNgvvWILAKK+VwIJyTbwvS96XYxlo5Q3x1K8jvKuyzehUrIEppQXhW4E8nG7rsbAanaDB1A/XXOM5pNkBvkQmxAzsPTqE2Pqs6MqUpgqTIJHh1XSUfFAngaexnYyq1btyPVBPKui8rORNZKwbA0tMAq7msDBIe29uh6lUrwrylS50xIpWjoERK2rDP/6Ie05CKXRGsk8oJQZ8pFQaQb0nQIq4LNpgwuiqh655u+K/jgP8KSEskMEqKGCR0qdtxh/4Z44P3cYSL9MGouHAgmwxXjHw1/64nF1T95rREEPaKY1O0O8vi2U026Bdx79TNQpPAdzxEH6d7vhL3yngE1IZ7SeP7SifH+rbFKD9yUH590FIGIUdN7hVTbYVj+H/C8uB9+UCfQnA4D5yhALyVmmGjQLVh4GOh0npThnJpTgaztfEIxE7d6oeY43lmUvwGuEx8OeETOR6DaK1wuywCeM9iCXVPIyceKtj9EymLVM9hUCK0PZYOC+qL1ZOwruC7dMvo5jHdGOPsMwEI=
  - secure: FltRhxajq/aPAyMY9w+sC9FOL+AjhbBjNq+lv4aFljYIT3evaIgXWbHH4GbWs+4QrVedW1bcV2JjZSDESUKz+xBTRwdfU7PDlF9Nvml3Jgn5RPViPCkNkYm/Y4NT7b3z/avE/tBtYmAiTVE+MLQJM2AkA7XfBcMnkvHVisruOvoYEKPBj89epPSInQHJwDLjb5nhtAMG7iwSZPHjbnK4D88OWFGIGPDOYaX2Y+siwqlWR1UCgNaeWX3xm6VPGMw2sILBwdkWjEtWRx3tdtuKKbYYuUXWV7xKLeeHM5+qJLXYmOngO6Ydzm3ZF8sSbjuDKS5OGFwnLQfOMw7YaY2MCljJhuJKgTbXYu5yugBl8nz5BpPH1F4vURSQF7Fzhyxrp/DlQGwcLb2lpulE/MzFPa5yihpiv69ApzvEkgvBEV5TvXFipBW1m3ACJmzv2aDlyinBabp/r4PyWxiUZdz0U/Wj1SQhVVJOGbnJXwq+EluEuSo4Uscq8BJbA30lNPFcuCJyEl7iqgFBkMrbHhQQCfK5tWD79PwE49bz2PQa/E1JmwU4MkCSnXiMwSl+Z1/HQBGSE4vsvZYuA4yzbEPKRaUhxo0WPMGnbUIclfKB7VvSvGZpnIoDGzEPHK+r7QjNDbgQlnGdVWvAGtc/auqLlJIY5GRydW6bIPEP6hdzk9Q=
  - secure: rs5dOakPcACgqE4G26FEBObzp+4/hPPXgO89uy1a/kJjjJKprGV7n0QsCTe4pDLupgoCbffbg7hT1CgiS9uhJx+toBqqu3llbqn6/3QgpHTf7eE7rkouYOgSdRRH5NDAoAV74aMWPBlj3cAWQBjLEgGNG8GVP5k4swBGWVAu9G3Ul4TQ19kUdvUfGXoU0ovL9tU/3tjoLgPDHYgnRgJ1Q5qDFruHxKdND+k7a+EMS6fMiMYS9nSzSZNvr+FJRY6yNiA7WjP9Ae5kf8UrWcB3gY1jVDFLOZK+KKiHOLMF84XelDgTSE3KjbqJhdAwovY/cDAPHszQsu/H3UqGHmn8uukyq4SP/RIgSfdIAEdII4PfduTJnCMGOZG3qbglYkOEIWhAPX7RrQuNwjlexrOc8iIL+U9OWNvyP6cICKOrMsfjBUJj0V10cAqt9KY2ELuGweSGIO7EhcrI6qxExbJbYVlyfaMRfyRZoUoabotF+WG+CsRScaTFC+werWiKCzj05DXPmTxPmCGDlXMhQkFhTzA7Q0NcrU23N0AzzpaIF23d3+Ljgl4HG1aBQ/yxDwd9YYsaeKFFgcxzLPK1Jdo+RRnWrs03qVkBxhYaoyQlxNEF9sgIP8dE7aWWcilgSMkBgE6kUGaUoZmzPlLO550rcH93ObGFXj1VwGh1bBNa9dA=
  - secure: TpxXndZROMO2pc7VuGEp+j6tDbdTyYc8TcsZCKtr8MvlA3Z8KVjdzbHGkplHdwdZzlP3Sq+OXw4ay5pbPsTQeNbQWxYTZ6Mx4xb+o07uw9tQcxc0f/dpASk+CWVuMocCmFSDHhmbfNktHyk8RGNE1l0Wjm350wU+hK/82co5DSf7DxWuOjEfcdv76X0fAzTrEtcocfCmsEB0Bnm2n89TlUfv13cfRU++pQ8wMm4bo5663YXMC6H/GU56Vmt7ojuN7Xi6e/HRghE6+2MkW+781CswPHvE1vkLIAWnRmE3qFFwj5PiJcCM36h7cF+nZVuhu6LVNINyapvyM77OtmM1LeygyXpzNA7wxXEGXTlnwpaRZtuPRTHKHlSWM+AsvrW/ZGOC7WlW0lLUTeyV3P/LrEuQsRomNobFBoHxfbrn0vTPPkn/QjS4Cm9GCAy3vfq3MImOdmdHIYrgjK8Zj2dUMzq7VnhCYEfUn9PzvVzTNj5gY1n9Oa9jq86Jy/oqGb8/UrM2Y27vCJ6FebE7owwPBH5U5fwgNw1kpt+WKYBkMhjipeniEeaMYCm4WV7KtPaPVF6KHhJcRuXncL4UHc3V6QC+6ifSt609X9oz39QliVDVh6imU8R1zsPuaLwp7PGLTXxwwWjw122m+dL8ySa3JaaHKwfhLuywPOu8k3uyKTs=
