sudo: false
language: scala
scala:
  - 2.12.4

matrix:
  include:
  - env: SCALAJS_VERSION="0.6.22"
  - env: SCALAJS_VERSION="1.0.0-M2"

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot/
before_cache:
  # Tricks to avoid unnecessary cache updates
  - find $HOME/.ivy2 -name "ivydata-*.properties" -delete
  - find $HOME/.sbt -name "*.lock" -delete
  - du -sh $HOME/.sbt/boot
  - du -sh $HOME/.ivy2/cache

script: sbt ++$TRAVIS_SCALA_VERSION compile

deploy:
  on:
    tags: true

before_install: |
  if [ $TRAVIS_PULL_REQUEST = "false" ]; then
    openssl aes-256-cbc -K $encrypted_0261605d70ea_key -iv $encrypted_0261605d70ea_iv -in travis/secrets.tar.enc -out travis/secrets.tar -d
    tar xv -C travis -f travis/secrets.tar;
  fi

after_success:
  - if [ $TRAVIS_PULL_REQUEST = 'false' ]; then sbt ++$TRAVIS_SCALA_VERSION releaseEarly;
    fi
