sudo: false
language: scala
scala:
  - 2.12.4
jdk: oraclejdk8
cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot/
before_cache:
  # Tricks to avoid unnecessary cache updates
  - find $HOME/.ivy2 -name "ivydata-*.properties" -delete
  - find $HOME/.sbt -name "*.lock" -delete
  - du -sh $HOME/.sbt/boot
  - du -sh $HOME/.ivy2/cache

script: sbt ++$TRAVIS_SCALA_VERSION compile
